version: '3.5'

services:
  node-exporter:
    image: flaviostutz/docker-swarm-node-exporter
    ports:
      - "9100:9100"
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    networks:
      - monitornet

networks:
  monitornet:
    external: true
