version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitornet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://192.168.60.101/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitornet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  node_exporter:
    image: prom/node-exporter:latest
    networks:
      - monitornet
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    deploy:
      mode: global  # chạy trên tất cả các node
      placement:
        constraints:
          - node.platform.os == linux

networks:
  monitornet:
    external: true

volumes:
  prometheus_data:
  grafana_data:

configs:
  prometheus_config:
    file: ./prometheus.yml
