version: "3.8"

configs:
  nginx_config:
    file: ./nginx.conf
  nginx_index:
    file: ./index.html

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
      - source: nginx_index
        target: /usr/share/nginx/html/index.html
    networks:
      - coinswarmnet
      - loggingnet
      - monitornet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  coinswarmnet:
    external: true
  loggingnet:
    external: true
  monitornet:
    external: true
