version: "3.8"

configs:
  nginx_config:
    file: ./nginx.conf # Path to the nginx.conf file on the manager node

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf # Path inside the container
    networks:
      - coinswarmnet
      - loggingnet
      - monitornet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  coinswarmnet:
    external: true
  loggingnet:
    external: true
  monitornet:
    external: true
