global:
   scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporters'
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: A
        port: 9100
  - job_name: 'prometheus'
    static_configs:
    - targets: ['192.168.60.101:9090']

remote_write:
  - url: "http://192.168.60.101/influxdb-write/"
